app = "zhorben-pamyataj-4a00afef-27ff-4b3f-b514-7b84f2a312be"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'
DEPLOY_ID = 'c924531b-599c-4fd2-b569-caf65177e63e'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
